### ISSUE TITLE
Can't read/write from CanvasPixelArray

### ISSUE THREAD

**Issue by mkaemmerer** [purescript-contrib/purescript-canvas#18]
It seems the underlying type of ImageData is a [Uint8ClampedArray](https://developer.mozilla.org/en-US/docs/Web/API/ImageData/data). Giving it a proper type instead of * would make it possible to read and write image data. As it is right now, ```getImageDataPixelArray``` is just about useless because it produces a value that no other function knows how to consume (without using the FFI).

These libraries could be useful
- https://github.com/purescript-contrib/purescript-arraybuffer-types
- https://github.com/purescript-contrib/purescript-arraybuffer

**Comment by mkaemmerer** [comment]
Would be willing to PR if what I'm suggesting makes any sense.

**Comment by paf31** [comment]
I agree it's pretty useless (without the FFI) right now. I think we have to be a bit careful about what we allow, since I'm not sure if it's always possible to treat the image data like an array, but I might be wrong. Maybe let's come up with something though, and we can iterate on it.

**Comment by asolove** [comment]
I'm also interested in getting access to the pixel data. @paf31 would you be interested in accepting an updated version of #19? `Uint8ClampedArray` is definitely the right type (see https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas).

**Comment by paf31** [comment]
Yes, sounds good, thanks. The `data` property is certainly an `Uint8ClampedArray`, and that type exists in `purescript-arraybuffer-types`.

**Comment by paf31** [comment]
Since `ImageData` is now defined as

```
type ImageData = { width :: Int, height :: Int, data :: Uint8ClampedArray }
```

this should no longer be an issue (although there is also #36 to sort out...)
