### ISSUE TITLE
tryLoadImage callback is invoked eagerly

### ISSUE THREAD

**Issue by ianthehenry** [purescript-contrib/purescript-canvas#39]
When evaluated, `tryLoadImage` will invoke its callback with `Nothing` immediately, then attempt to load the image, then invoke its callback again once the correct value has been determined.

**Comment by paf31** [comment]
Thanks for the bug report. Are you able to see if the error callback is being run?

**Comment by paf31** [comment]
Of course, we should only call the callback once in any case.

**Comment by ianthehenry** [comment]
Hello! Sorry. My Github notifications got out of hand last week and I didn't see this.

In the case where the image load succeeds, the callback is invoked once eagerly with `Nothing` (*not* in response to an `"error"` event) and once again with `Just image`.

In the case where the load errors, the callback is invoked once eagerly with `Nothing` and never invoked again.

That seemed weird at first, but it's not really.

          return $foreign.tryLoadImageImpl(path)(k(Data_Maybe.Nothing.value))(function ($28) {
              return k(Data_Maybe.Just.create($28));
          });

`e` is the result of invoking `k`, when I expected it to be the result of partially applying `k`.

But also, like, morally this is sort of... correct? It's just eagerly evaluating the `Eff` value to use in the error case, even though it might not need it. After all, determination of the effect is pure, so "predictive evaluation" isn't... *wrong* here. But I expected a degree of laziness that was not present.

So it's only really a performance bug, and then only barely. Just surprising to me. I only noticed this because I was unsafely insisting the value was there so I didn't have to branch -- which it was, sort of. I'm still getting used to strict evaluation.

In my app I switched over to this instead:

```purescript
foreign import loadImage :: forall e. String -> Aff (| e) CanvasImageSource
```

```javascript
exports.loadImage = function(src) {
    return function (onSuccess, onError) {
        var img = new Image();
        img.src = src;
        img.addEventListener("load", function() {
            onSuccess(img);
        }, false);
        img.addEventListener("error", onError, false);
    }
}
```

But adding a dependency to `Aff` feels weird for this project, so I don't know if there's much to do.

**Comment by paf31** [comment]
The function should not be called eagerly as you describe. It's a bug if that's happening :)

**Comment by paf31** [comment]
Also, adding an `aff` dependency should not be necessary.

**Comment by paf31** [comment]
Without having run it yet, the code does look correct. How are you calling `tryLoadImageImpl`?

**Comment by mtolly** [comment]
It's not that the `Eff` function is being called eagerly -- it's that this line:

```
tryLoadImage path k = tryLoadImageImpl path (k Nothing) (k <<< Just)
```

is calling `k Nothing` eagerly. This is not a problem if you are using `Eff` properly. I ran into this issue because I had this (poorly written) part to emulate the old `withImage`:

```
withImage path f = tryLoadImage path $ \mimg -> case mimg of
  Just img -> f img
  Nothing  -> unsafeThrow $ "panic! could not load image from path: " <> path
```

The fix was of course replacing the `unsafeThrow` with `throwException` and adding the `EXCEPTION` effect where needed. So this isn't a bug; the evaluation is just unexpected if you are cheating with error handling like I was :)

**Comment by hdgarrood** [comment]
Closing as @mtolly's analysis seems to be the most likely explanation as to what's going on here. Please reopen if I'm missing something.
