### ISSUE TITLE
Uncaught ReferenceError: AlignLeft is not defined

### ISSUE THREAD

**Issue by ervasive** [purescript-contrib/purescript-canvas#40]
The [example](https://github.com/paf31/purescript-book/blob/master/exercises/chapter9/src/Example/Rectangle.purs) from "PureScript by Example" gives me that exception:

```
Uncaught ReferenceError: AlignLeft is not defined
    at PS.Graphics.Canvas (Main.js:287)
    at Main.js:346
```

- psc 0.10.6
- Chrome 56.0.2924.87 (64-bit)

**Comment by garyb** [comment]
I think that will be down to this: purescript/purescript#2642

**Comment by hdgarrood** [comment]
Yes, looks like it. Upgrading your compiler should fix this; if it doesn't, could you please comment with more detailed repro steps?
