### ISSUE TITLE
Operations on context returning unit

### ISSUE THREAD

**Issue by jacereda** [purescript-contrib/purescript-canvas#42]
Should there be operations on context returning unit?
Starting with 0.11, operating on the canvas becomes a bit uglier due to the explicit discard:

    _ <- Canvas.scale s ctx

Perhaps we could have things like:

    Canvas.scale_ s ctx

and keep the current operations as they are to allow chaining.

**Comment by gabejohnson** [comment]
Would a better option be to add a `Discard` instance for `Context2D`?

**Comment by gabejohnson** [comment]
My reasoning is that `ctx` is mutable so we don't really care about the return value anyway.

**Comment by hdgarrood** [comment]
Resolved by #53.
