### ISSUE TITLE
Rotate does not work

### ISSUE THREAD

**Issue by stifspear** [purescript-contrib/purescript-canvas#49]
Hello sir,

I am stuck at this problem for quite some time now. I am trying to rotate a canvas but failing. What might be wrong in this snipped. I am using canvas library. It is compiling fine but the canvas does not rotate. I have tried differed rotation angles.

```purescript
rotateLogo :: Eff (canvas :: CANVAS) Unit
rotateLogo = void $ unsafePartial do
  Just canvas <- getCanvasElementById "canvas"
  ctx <- getContext2D canvas
  void $ rotate (pi * 1.5 ) ctx
  translate { translateX : 0.0, translateY : 0.0 } ctx
```

**Comment by paf31** [comment]
This is not how rotation works with HTML5 Canvas. I'd recommend reading the canvas docs first, but the idea is that it modifies the state of the context, for future renders. It doesn't modify the existing content of the canvas.
